### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by aistein** [aamini/introtodeeplearning_labs#9]
Will you please post a link to the free docker image on dockerhub?  I cannot find it.

**Comment by aistein** [comment]
This works for me!  Sorry if that was a silly question, I'm a bit new to docker.  Also I'm running this series of labs on a gcloud computer instance of ubuntu 16.04, so I was a bit thrown off by the instructions for windows.  Anyway, issue closed! Cheers!

**Comment by aamini** [comment]
Awesome! Running on Ubuntu is a much better option than windows -- follow up if you have any other issues :)

**Comment by aistein** [comment]
Thanks!  Actually, I do have some questions... I'm actually pursuing these labs as part of a school project - software profiling of tensorflow code.  The end goal is to be able to analyze potential inefficiencies (from the GPU perspective) of standard deep-learning code... which I suspect to be likely given how high-level these frameworks are.  Given that, here are my questions

- do the labs running on docker use tensorflow-GPU?
- how can I get terminal access to the docker image (is that even a thing I can do?).  I'd like to run the native nvidia profiler (nvprof) on the code from these labs.
- Just in case I can't get a terminal... Is it straightforward and simple to install the dependencies needed to run these labs on my gcloud instance?  I've already got tensorflow and CUDA and all that installed, but I couldn't quite get it working.

Sorry if this is terribly long!

**Comment by aamini** [comment]
This sounds awesome! If you're able to share the results of your project then I'd be very interested! 

> do the labs running on docker use tensorflow-GPU?

Yes, they will work with either CPU or GPU versions of tensorflow

> how can I get terminal access to the docker image (is that even a thing I can do?). I'd like to run the native nvidia profiler (nvprof) on the code from these labs.

Yes, this is definitely possible! You can use the `-it --entrypoint /bin/bash` arguments to enter a bash terminal after starting. So your full command to launch docker becomes: 
`docker run -it -p 8888:8888 -p 6006:6006 --entrypoint /bin/bash -v /path/to/introtodeeplearning_labs:/notebooks/introtodeeplearning_labs mit6s191/iap2018:labs`

This will give you a normal terminal that you can run commands from. You might find it useful to open multiple windows inside the docker -- you can use [tmux](https://medium.com/actualize-network/a-minimalist-guide-to-tmux-13675fb160fa) for this. Just update the docker system with `apt update` and `apt install tmux` to install. Finally, you just need to open jupyter by running `jupyter notebook`.

> Just in case I can't get a terminal... Is it straightforward and simple to install the dependencies needed to run these labs on my gcloud instance? I've already got tensorflow and CUDA and all that installed, but I couldn't quite get it working.

It should be very straightforward to install the dependencies if you are on Ubuntu (and don't want to use docker). We chose to use docker since it made the installation process easier during the class when people had many different types of machines. In general, docker provides a great way to standardize the software running on many different platforms.

**Comment by aistein** [comment]
Thanks so much for the information! I'll give it a whirl!

**Comment by aistein** [comment]
Hi Alexander,

I didn't end up using y'all's project for the performance demonstrations, but they most definitely helped to steer me in the right direction!  In case you're interested, here's the page for the final project:

https://aistein.github.io/dlprof/

Cheers,
Alex
